CODES FOR CREATING TABLES

In [ ]:
%%sql
CREATE TABLE IF NOT EXISTS devices (
   name TEXT PRIMARY KEY,
   loc TEXT NOT NULL,
   level TEXT NOT NULL,
   PRIMARY KEY (name)
   FOREIGN KEY (name) 
      REFERENCES smartthings (name)
)

In [ ]:
%%sql
CREATE TABLE IF NOT EXISTS smartthings (
   name TEXT NOT NULL,
   epoch TEXT NOT NULL,
   capability TEXT NOT NULL,
   attribute TEXT NOT NULL,
   value TEXT NOT NULL,
   unit TEXT,
   PRIMARY KEY (name,epoch,attribute)
   FOREIGN KEY (name) 
      REFERENCES devices (name)
)

In [ ]:
%%sql
CREATE TABLE IF NOT EXISTS p1e (
   epoch INTEGER PRIMARY KEY,
   ImportT1kWh FLOAT,
   ImportT2kWh FLOAT,
   ExportT1kWh FLOAT,
   ExportT2kWh FLOAT,
   PRIMARY KEY (epoch)
   FOREIGN KEY (epoch) 
      REFERENCES smartthings (epoch)
)

In [ ]:
%%sql
CREATE TABLE IF NOT EXISTS p1g (
   epoch INTEGER PRIMARY KEY,
   Total_gas_used FLOAT,
   PRIMARY KEY (epoch)
   FOREIGN KEY (epoch) 
      REFERENCES smartthings (epoch)
)

Exploring Data to create Dataset

In [74]:
import pandas as pd
import glob

file_list = glob.glob('data/smartthings/smartthings.*')

# Read and concatenate all matching files into a single DataFrame
smart_things = pd.concat([pd.read_csv(f, sep='\t') for f in file_list], ignore_index=True)

In [75]:
filt = smart_things[~smart_things.duplicated()]

In [76]:
# Of duplicated entries
smart_things.shape[0]-filt.shape[0]

665211

In [77]:
filt[filt.duplicated(subset=['name', 'epoch', 'attribute'])]

,loc,level,name,epoch,capability,attribute,value,unit
243,bathroom,1st,Bathroom (flower),2022-10-12T06:45:54Z,switch,switch,on,NaN
947,bathroom,1st,Bathroom (sensor eye),2022-10-15T08:25:48Z,motionSensor,motion,active,NaN
1267,bathroom,1st,Bathroom (sensor eye),2022-10-15T20:20:41Z,motionSensor,motion,active,NaN
1279,bathroom,1st,Bathroom (sensor eye),2022-10-15T20:36:55Z,motionSensor,motion,active,NaN
1464,bathroom,1st,Bathroom (flower),2022-10-16T08:13:45Z,switch,switch,off,NaN
...,...,...,...,...,...,...,...,...
2390268,bathroom,1st,Bathroom (sensor eye),2025-04-09T07:16:32Z,illuminanceMeasurement,illuminance,2635,lux
2390269,bathroom,1st,Bathroom (sensor eye),2025-04-09T07:16:32Z,illuminanceMeasurement,illuminance,1651,lux
2391986,bathroom,1st,Bathroom (sensor eye),2025-04-09T17:39:57Z,motionSensor,motion,active,NaN
2394818,bathroom,1st,Bathroom (sensor eye),2025-04-10T21:56:27Z,motionSensor,motion,active,NaN
2397826,bathroom,1st,Bathroom (sensor eye),2025-04-12T16:53:23Z,motionSensor,motion,active,NaN

In [81]:
filt[filt.epoch.duplicated() & filt.name.duplicated()]

,loc,level,name,epoch,capability,attribute,value,unit
13,kitchen,ground,Door (main),2022-10-09T21:45:58Z,signalStrength,lqi,184,NaN
14,kitchen,ground,Door (main),2022-10-09T21:45:58Z,signalStrength,rssi,-54,dBm
24,kitchen,ground,Door (main),2022-10-09T23:26:16Z,signalStrength,lqi,188,NaN
25,kitchen,ground,Door (main),2022-10-09T23:26:16Z,signalStrength,rssi,-53,dBm
28,kitchen,ground,Door (main),2022-10-10T02:46:51Z,signalStrength,rssi,-52,dBm
...,...,...,...,...,...,...,...,...
2397888,floor,1st,Blue Room (printer),2025-04-12T17:12:42Z,legendabsolute60149.signalMetrics,signalMetrics,"2025/04/12 GMT: 17:12, LQI: 200 ... rssi: -81",NaN
2397891,bathroom,1st,Bathroom (sensor eye),2025-04-12T17:12:52Z,motionSensor,motion,inactive,NaN
2397909,floor,1st,Blue room (move aeotec),2025-04-12T17:14:28Z,ultravioletIndex,ultravioletIndex,1,NaN
2397937,floor,1st,Blue room (move aeotec),2025-04-12T17:19:36Z,tamperAlert,tamper,detected,NaN
2397949,floor,1st,Blue room (move aeotec),2025-04-12T17:23:24Z,ultravioletIndex,ultravioletIndex,0,NaN

In [79]:
import calendar
#calendar.timegm(filt.epoch)

calendar.timegm(pd.to_datetime(filt['epoch']))

TypeError: 'Timestamp' object cannot be interpreted as an integer

In [ ]:
filt.epoch.dtype

Create Database

In [ ]:
%load_ext sql
%sql sqlite:///energy.db

%%sql
CREATE TABLE IF NOT EXISTS

In [ ]:
import sqlalchemy as sa
sa.create_engine("sqlite:///energy.db")